server:
  port: ${PORT:4403}

spring:
  profiles:
    active: dev
  application:
    name: e-commerce-api
  datasource:
    url: ${MY_SQL_URL}
    username: ${MY_SQL_USERNAME}
    password: ${MY_SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION}
    paystack-test-secret-key: ${PAYSTACK_TEST_SECRET_KEY}
    paystack-test-public-key: ${PAYSTACK_TEST_PUBLIC_KEY}
    live-url: ${LIVE_URL}
    frontend-url: ${FRONTEND_URL}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
#          facebook:
#            client-id:
#            client-secret:
#            scope: public_profile,email

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    #    path: /swagger-ui.html
    path: /swagger
    operations-sorter: method
