server:
  port: 4403

spring:
  application:
    name: e-commerce-api
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_project_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 1800000 #30 minutes

springdoc:
  swagger-ui:
    path: /swagger
